channels:
  - quansight/label/omnisci
  - conda-forge
dependencies:
  - altair
  - bokeh
  - conda
  - geoviews
  - quansight/label/omnisci::omnisci-examples
  - hvplot >=0.7.1
  - holoviews >= 1.14.0
  - ibis-framework >=1.4
  - ibis-vega-transform >=5.3.0
  - intake >=0.5.3
  - intake-omnisci
  - jaeger <1.22.0
  - jaeger-browser
  - jupyterlab 3.*
  - jupyter-jaeger >=1.0.4
  - nodejs >=12
  - notebook
  # NOTE: numpy pinned to fix the following error:
  #   AttributeError: type object 'object' has no attribute 'dtype'
  - numpy <1.20
  - omnisci-pytools
  - pandas
  - pip
  - pydot
  - pymapd >=0.24
  - python 3.8.*
  - rbc >=0.4
