channels:
  - quansight/label/omnisci
  - conda-forge
dependencies:
  - intake >=0.5.3
  - intake-omnisci
  - geoviews
  - omnisci-pytools
  - jupyter-jaeger
  - pandas <0.26
  - pydot
  - pymapd
  - pyarrow >=0.15.0
  - python >=3.7
  - ibis-framework
  - jupyterlab >=2.2
  # local depencencies
  - ibis-framework 1.3.0
  - holoviews 1.13.4
  - hvplot 0.6.0
  # needed for pkg building
  - conda
