channels:
  - quansight/label/omnisci
  - conda-forge
dependencies:
  - altair
  - arrow-cpp 0.15.0
  - bokeh
  - conda
  - geoviews
  - quansight/label/omnisci::hvplot
  - quansight/label/omnisci::omnisci-examples
  - holoviews >= 1.14.0
  - ibis-framework >=1.4
  - intake >=0.5.3
  - intake-omnisci
  - jaeger
  - jupyterlab >=2.2,<3
  - jupyter-jaeger
  - nodejs >=12,<15
  - notebook
  - omnisci-pytools
  - pandas
  - pip
  # pyarrow 0.15.1 is raising an error: Library not loaded: @rpath/libprotobuf.22.dylib
  - pyarrow 0.15.0
  - pydot
  - pymapd >=0.24
  - python 3.7.*
  - rbc >=0.4
  - pip:
    # as it is not recognized by conda constructor
    # it should installed by post-install.sh
    - ibis-vega-transform
