{% set version = "1.13.4" %}

package:
  name: holoviews
  version: {{ version }}

source:
  url: https://github.com/holoviz/holoviews/archive/c26b721fa9d344e72ee280718936a046c3c60507.zip
  sha256: 6466a7968ead371ac5dfee2eb69699e13b3d7a2dcaf68242df2b7e17b3f549e1

build:
  number: 99
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - holoviews = holoviews.util.command:main

requirements:
  host:
    - python
    - pip
    - pyct
    - param >=1.6.1,<2.0
  run:
    - python
    - param >=1.9.3,<2.0
    - panel >=0.7.0
    - numpy >=1.0
    - pandas >=0.20.0
    - matplotlib-base >=2.2
    - bokeh >=1.1.0
    - notebook
    - ipython >=5.4.0
    - pyviz_comms >=0.7.4
    # new dependency
    - ibis-framework >=1.3.0

test:
  imports:
    - holoviews
  commands:
    - pip check
    - holoviews -h
  requires:
    - pip

about:
  home: www.holoviews.org
  summary: Stop plotting your data - annotate your data and let it visualize itself.
  description: |
    HoloViews is an open-source Python library designed to make data analysis
    and visualization seamless and simple. With HoloViews, you can usually
    express what you want to do in very few lines of code, letting you focus on
    what you are trying to explore and convey, not on the process of plotting.
  license: BSD-3-Clause
  license_file: LICENSE.txt
  dev_url: https://github.com/ioam/holoviews
  doc_url: http://holoviews.org/getting_started/index.html

extra:
  recipe-maintainers:
    - jlstevens
    - philippjfr
    - basnijholt
