{% set name = "omnisci-datascience-tools" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  noarch: generic
  number: 0

requirements:
  run:
    - altair
    - arrow-cpp
    - bokeh
    - geoviews
    - hvplot
    - holoviews >=1.14.0
    - ibis-vega-transform
    - ibis-framework >=1.4
    - intake >=0.5.3
    - intake-omnisci
    - jaeger
    - jupyterlab >=2.2
    - jupyter-jaeger
    - nodejs >=12
    - notebook
    - omnisci-pytools
    - pandas
    - pip
    - pyarrow
    - pydot
    - pymapd >=0.24
    - pytest
    - python 3.7.*
    - rbc >=0.4

test:
  imports:
    - ibis.backends.omniscidb
    - pymapd
    - intake
    - altair
    - ibis_vega_transform
    - geoviews
    - holoviews
    - graphviz
    - pydot

about:
  home: https://github.com/Quansight/omnisci-datascience-installer
  license: Other
  license_family: Other
  license_file: ../constructor/license.txt
  summary: 'OmniSci Data Science Tools'

extra:
  recipe-maintainers:
    - xmnlab
