{% set name = "omnisci-datascience-tools" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: ../

build:
  noarch: generic
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  run:
    - altair
    - arrow-cpp 0.15.0
    - bokeh
    - geoviews
    - hvplot
    - holoviews >=1.14.0
    - ibis-framework >=1.4
    - ibis-vega-transform
    - intake >=0.5.3
    - intake-omnisci
    - jaeger
    - jupyterlab >=2.2,<3
    - jupyter-jaeger
    - nodejs >=12,<15
    - notebook
    - omnisci-pytools
    - pandas
    - pip
    # pyarrow 0.15.1 is raising an error: Library not loaded: @rpath/libprotobuf.22.dylib
    - pyarrow 0.15.0
    - pydot
    - pymapd >=0.24
    - pytest
    - python 3.7.*
    - rbc >=0.4

test:
  imports:
    - ibis.backends.omniscidb
    - pymapd
    - intake
    - altair
    - ibis_vega_transform
    - geoviews
    - holoviews
    - graphviz
    - pydot

about:
  home: https://github.com/Quansight/omnisci-datascience-installer
  license: Other
  license_family: Other
  license_file: ../constructor/license.txt
  summary: 'OmniSci Data Science Tools'

extra:
  recipe-maintainers:
    - xmnlab
