{% set name = "omnisci-datascience-tools" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: ../

build:
  noarch: generic
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  run:
    - altair
    - bokeh
    - geoviews
    - hvplot >=0.7.1
    - holoviews >=1.14.0
    - ibis-framework >=1.4
    - ibis-vega-transform >=5.3.0
    - intake >=0.5.3
    - intake-omnisci
    - jaeger <1.22.0
    - jaeger-browser
    - jupyterlab 3.*
    - jupyter-jaeger >=1.0.4
    - nodejs >=12
    - notebook
    # NOTE: numpy pinned to fix the following error:
    #   AttributeError: type object 'object' has no attribute 'dtype'
    - numpy <1.20
    - omnisci-pytools
    - pandas
    - pip
    - pydot
    - pymapd >=0.24
    - pytest
    - python 3.8.*
    - rbc >=0.4

test:
  imports:
    - ibis.backends.omniscidb
    - pymapd
    - intake
    - altair
    - ibis_vega_transform
    - geoviews
    - holoviews
    - graphviz
    - pydot
  commands:
    - jupyter labextension list 2>&1 | grep -ie "jupyter-jaeger.*OK"
    - jupyter labextension list 2>&1 | grep -ie "ibis-vega-transform.*OK"

about:
  home: https://github.com/Quansight/omnisci-datascience-installer
  license: Other
  license_family: Other
  license_file: ../constructor/license.txt
  summary: 'OmniSci Data Science Tools'

extra:
  recipe-maintainers:
    - xmnlab
