name: constructor

on:
  push:
    branches: [ master ]
    tags: ['*']
  pull_request:
    branches: [ master ]

jobs:
  construct:
    strategy:
      matrix:
        python-version: [3.8]
        os: [macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 120

    env:
      PYTHON_VERSION: ${{ matrix.python-version }}
      IMAGE_OS: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    - name: configure
      if: matrix.os == 'macos-latest'
      run: |
        ulimit -S -n 204800
        sudo sysctl -w kern.maxfiles=204800
        sudo sysctl -w kern.maxfilesperproc=245670

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        activate-environment: omnisci-ds-installer
        channels: quansight/label/omnisci,conda-forge

    - name: install dependencies
      run: |
        conda install -y constructor conda-build
        if [[ $IMAGE_OS == 'ubuntu-latest' ]]; then
          wget https://repo.anaconda.com/pkgs/misc/conda-execs/conda-latest-linux-64.exe -O conda.exe
        else
          wget https://repo.anaconda.com/pkgs/misc/conda-execs/conda-latest-osx-64.exe -O conda.exe
        fi

    - name: run constructor for pkg
      id: pkg_name
      if: matrix.os == 'macos-latest'
      run: |
        constructor --conda-exe conda.exe constructor/pkg
        PKG_NAME=$(ls omnisci-*-MacOSX-x86_64.pkg)
        echo "::set-output name=filename::$PKG_NAME"

    - name: run constructor for sh
      id: sh_name
      run: |
        constructor --conda-exe conda.exe constructor/sh
        SH_NAME=$(ls omnisci-*.sh)
        echo "::set-output name=filename::$SH_NAME"

    - name: install sh package
      run: bash ${{ steps.sh_name.outputs.filename }} -b

    - name: test imports
      run: |
        source conda_activate.sh
        python -c "import ibis"
        python -c "import pymapd"
        python -c "import intake"
        python -c "import altair"
        python -c "import ibis_vega_transform"
        python -c "import geoviews"
        python -c "import holoviews"
        python -c "import graphviz"
        python -c "import pydot"
        python -c "from ibis.expr.operations import RowID"

    - name: Test jupyter-lab extensions
      run: |
        source conda_activate.sh
        jupyter labextension list 2>&1 | grep -ie "jupyter-jaeger.*OK"
        jupyter labextension list 2>&1 | grep -ie "ibis-vega-transform.*OK"

    - name: test notebooks with external connection
      if: matrix.os == 'macos-latest'
      run: |
        source conda_activate.sh
        # install nbconvert for the tests
        conda install -y nbconvert
        # run notebook tests
        bash test_notebooks.sh

    - name: start up omniscidb server
      if: matrix.os == 'ubuntu-latest'
      run: |
        source conda_activate.sh
        cd ${CONDA_PREFIX}/opt/omnisci-examples
        conda install -y docker-compose
        docker-compose build omniscidb
        docker-compose up -d omniscidb
        sleep 5

    - name: test notebooks with internal connection
      if: matrix.os == 'ubuntu-latest'
      run: |
        source conda_activate.sh
        # install nbconvert for the tests
        pip install nbmake pytest
        # run notebook tests
        cd ${CONDA_PREFIX}/opt/omnisci-examples
        pytest --nbmake -vv

    - name: create release macos
      id: create_release_macos
      if: startsWith(github.ref, 'refs/tags/') && matrix.os == 'macos-latest'
      uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        allowUpdates: true
        replacesArtifacts: true
        tag: ${{ github.event.release.tag_name }}
        name: Release ${{ github.event.release.tag_name }}
        commit: master
        artifacts: ${{ steps.pkg_name.outputs.filename }},${{ steps.sh_name.outputs.filename }}
        artifactContentType: application/octet-stream
        body: Release ${{ github.event.release.tag_name }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: create release linux
      id: create_release_linux
      if: startsWith(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-latest'
      uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        allowUpdates: true
        replacesArtifacts: true
        tag: ${{ github.event.release.tag_name }}
        name: Release ${{ github.event.release.tag_name }}
        commit: master
        artifacts: ${{ steps.sh_name.outputs.filename }}
        artifactContentType: application/octet-stream
        body: Release ${{ github.event.release.tag_name }}
        token: ${{ secrets.GITHUB_TOKEN }}
