name: packaging

on:
  push:
    branches: [ master ]
    tags: ['*']
  pull_request:
    branches: [ master ]

jobs:
  macos:

    runs-on: macos-latest
    timeout-minutes: 60
    strategy:
      matrix:
        python-version: [3.7]

    env:
      PYTHON_VERSION: ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v2

    - name: configure
      shell: bash -l {0}
      run: |
        ulimit -S -n 204800
        sudo sysctl -w kern.maxfiles=204800
        sudo sysctl -w kern.maxfilesperproc=245670

    - uses: docker-practice/actions-setup-docker@master
      with:
        docker_channel: stable
        docker_version: 20.10

    - name: start docker compose for tests
      run: |
        # download the omnisci-example repo
        git clone --depth 1 https://github.com/Quansight/omnisci-examples.git
        # start services
        cd omnisci-examples && docker-compose start

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        activate-environment: omnisci-ds-installer
        channels: quansight/label/omnisci,conda-forge

    - name: install dependencies
      shell: bash -l {0}
      run: |
        conda install -y constructor conda-build
        wget https://repo.anaconda.com/pkgs/misc/conda-execs/conda-latest-osx-64.exe -O conda.exe

    # - name: run constructor for pkg
    #   id: pkg_name
    #   shell: bash -l {0}
    #   run: |
    #     constructor --conda-exe conda.exe constructor/pkg
    #     PKG_NAME=$(ls omnisci-*-MacOSX-x86_64.pkg)
    #     echo "::set-output name=filename::$PKG_NAME"

    - name: run constructor for sh
      id: sh_name
      shell: bash -l {0}
      run: |
        constructor --conda-exe conda.exe constructor/sh
        SH_NAME=$(ls omnisci-*-MacOSX-x86_64.sh)
        echo "::set-output name=filename::$SH_NAME"

    - name: test shell package
      run: |
        bash ${{ steps.sh_name.outputs.filename }} -b
        source conda_activate.sh
        python -c "import ibis.omniscidb"
        python -c "import pymapd"
        python -c "import intake"
        python -c "import altair"
        python -c "import ibis_vega_transform"
        python -c "import geoviews"
        python -c "import holoviews"
        python -c "import graphviz"
        python -c "import pydot"
        python -c "from ibis.expr.operations import RowID"
        # install nbmake for the tests
        pip install nbmake
        # run notebook tests
        pytest --nbmake -vv \
          omnisci-examples/notebooks/*.ipynb \
          omnisci-examples/notebooks/**/*.ipynb

    - name: tests tear down
      run: |
        cd omnisci-examples && /Library/Frameworks/Python.framework/Versions/2.7/bin/docker-compose stop

    - name: create release
      id: create_release
      if: startsWith(github.ref, 'refs/tags/')
      uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        allowUpdates: true
        replacesArtifacts: true
        tag: ${{ github.event.release.tag_name }}
        name: Release ${{ github.event.release.tag_name }}
        commit: master
        # artifacts: ${{ steps.pkg_name.outputs.filename }},${{ steps.sh_name.outputs.filename }}
        artifacts: ${{ steps.sh_name.outputs.filename }}
        artifactContentType: application/octet-stream
        body: Release ${{ github.event.release.tag_name }}
        token: ${{ secrets.GITHUB_TOKEN }}
